// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hadik_api.Data;

#nullable disable

namespace hadik_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220221145646_CreateInitial")]
    partial class CreateInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("hadik_api.Hadik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("SavedScore")
                        .HasColumnType("int");

                    b.Property<int>("SavedSnakeLenght")
                        .HasColumnType("int");

                    b.Property<int>("SavedSnakePosX")
                        .HasColumnType("int");

                    b.Property<int>("SavedSnakePosY")
                        .HasColumnType("int");

                    b.Property<int>("SavedVelocityX")
                        .HasColumnType("int");

                    b.Property<int>("SavedVelocityY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HadikSavedData");
                });

            modelBuilder.Entity("hadik_api.HadikParts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HadikSavedParts");
                });
#pragma warning restore 612, 618
        }
    }
}
